### ISSUE TITLE
Support for scoped modules

### ISSUE THREAD

**Issue by danielkcz** [eladnava/tldrlegal#1]
I made an issue in a `legally` dependency. This is just to keep track of it and update to a newer version if necessary once fixed.

https://github.com/franciscop/legally/issues/14

**Comment by eladnava** [comment]
@FredyC cool, I hope it gets fixed upstream.

**Comment by eladnava** [comment]
I submitted a PR:
https://github.com/franciscop/legally/pull/15

**Comment by eladnava** [comment]
PR merged! 😄 

Run the following to reinstall `tldrlegal` with the updated `legally` dependency:

```
npm update -g tldrlegal

cd my-project-with-scoped-dependencies/
tldrlegal
```

Thanks so much @franciscop for the quick merge. 👍
