### ISSUE TITLE
recursively walks entire project folder, rather than just node_modules

### ISSUE THREAD

**Issue by j2L4e** [eladnava/tldrlegal#11]
When you run `tldrlegal` it passes `cwd()` or another specified path down to `legally`. `legally` recursively walks that path. This can lead to pitfalls like build directories being included which can yield unexpected results.
I'd just pass `./node_modules` as a path, but https://github.com/eladnava/tldrlegal/blob/master/index.js#L24 prevents that.

My current workaround is `mkdir node_modules/node_modules && tldrlegal --folder $(pwd)/node_modules && rm -f node_modules/node_modules`.

**Comment by eladnava** [comment]
Published fix in `1.0.9`: https://github.com/eladnava/tldrlegal/commit/fc4e4f41d9e461b3219660982759aac765dd0667

**Comment by eladnava** [comment]
You can now run 
```
tldrlegal --folder ./node_modules/
```

**Comment by j2L4e** [comment]
Thanks!
