### ISSUE TITLE
Handle missing node_modules correctly

### ISSUE THREAD

**Issue by akaRem** [eladnava/tldrlegal#3]
If you scan some other dir than your project root, then utility shows 2 sections:
- License Obligation Summary (where everything is fine)
- Disclaimer

If anyone scans wrong dir by mistake, then I think it's better to explicitly say that there is no modules in this directory.

Moreover It would be very informative to show overall amount of scanned components..

**Comment by eladnava** [comment]
These are excellent suggestions, thanks so much!

I've implemented them both. 😄 

Running the CLI in a non-JavaScript folder yields the following error:

![screen shot 2017-02-23 at 1 10 04 pm](https://cloud.githubusercontent.com/assets/4394189/23256966/4a37d056-f9ca-11e6-9602-9034ad3f2ae1.png)

Running the CLI outputs the total number of checked packages:

![screen shot 2017-02-23 at 1 12 41 pm](https://cloud.githubusercontent.com/assets/4394189/23256976/56a787fa-f9ca-11e6-9a4b-c182f6418623.png)

These are available in version `1.0.4` of `tldrlegal` which has been published to npm.
