### ISSUE TITLE
Clarifying the `isIrrelevant` attribute

### ISSUE THREAD

**Issue by phillbaker** [eladnava/tldrlegal#6]
Thanks for all the work on this package, it's very helpful! I did want to clarify some of the reasoning about the `isIrrelevant` attribute, and propose a feature.

Several obligations have:

https://github.com/eladnava/tldrlegal/blob/de9e61b379751112cbf660a17e9b01de7f9df04f/metadata/obligationInfo.js#L23-L24

I assume this is under the assumption that locally when `npm` installs the dependency, the license is copied alongside the source?

I know this isn't legal advice, but I wanted to raise two other cases to see if you thought tldrlegal should sometimes show these obligations as relevant:

* when npm packages are included in a minified/concatenated "compiled" applications for use in either server side or client side scripts?
  * [this decent summary](https://www.tawesoft.co.uk/kb/article/mit-license-faq#if-i-use-mit-licensed-software-server-side-do-i-have-to-display-the-copyright-notice-or-disclaimer) seems to cover the server side - since it's not "distributed" the license obligation does not apply
  * however, is [client side code distributed](https://medium.com/@vovabilonenko/licenses-of-npm-dependencies-bacaa00c8c65#f87d) and thus [the obligation may apply](http://www.iusmentis.com/computerprograms/opensourcesoftware/license-notices-web-applications/)? It seems like [UglifyJS and its webpack plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) do include the license of package.json's `dependencies` in the output by default.
* when npm packages are included in binary distributions like react native?
  * from the same summary above, it seems like this is [closed source software where the obligation does apply](https://www.tawesoft.co.uk/kb/article/mit-license-faq#can-i-use-mit-licensed-code-in-closed-source-software). There are some examples of [displaying](https://stackoverflow.com/questions/6428353/best-way-to-add-license-section-to-ios-settings-bundle) these [acknowledgements](https://discordapp.com/acknowledgements) and [tools](https://github.com/mono0926/LicensePlist) to gather the licenses.

What do you think about adding `--binary` or `--clientside` flags which indicates the user is using npm packages in a distributed binary or clientside and ignore the `isIrrelevant` attribute in the output? Happy to contribute this myself, however, looking for feedback on the thinking and approach.

**Comment by eladnava** [comment]
Hi @phillbaker,
Nice to connect with you and thanks for the suggestion! 😄 

These are indeed some gray areas that I'm not entirely sure about from a legal perspective, but it would appear that for most open source package licenses in a binary distribution, the copyright notice and permission notice can safely be included in the documentation or EULA of the binary software and not distributed alongside the actual binary.

Would you say that it would suffice to provide a flag to `tldrlegal` which will simply ignore the `isIrrelevant` flag and warn about these obligations as well?

**Comment by phillbaker** [comment]
@eladnava that sounds good!

**Comment by eladnava** [comment]
@phillbaker Great! 😄

What do you think of labeling this flag as `--closed-source` to indicate that the solution is being distributed as closed-source (either binary or client-side with webpack for example) which would mean that the npm `LICENSE` files are not being distributed alongside it?

You would define the command-line argument here:
https://github.com/eladnava/tldrlegal/blob/5e52ee708e1a6153e0ca8caa9a660ebbc69a6d8a/index.js#L11-L14

And when this argument is passed in, `tldrlegal` will simply ignore the `isRelevant` attribute. You would probably modify the following function to check if the argument was passed in:
https://github.com/eladnava/tldrlegal/blob/5e52ee708e1a6153e0ca8caa9a660ebbc69a6d8a/lib/licensing.js#L10-L13

Would you like to submit a PR?

**Comment by phillbaker** [comment]
Sounds good, created #7.
